#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# .zshrc
  
# rbenv
eval "$(rbenv init -)"

# options
# Enable > into an existing file
setopt CLOBBER
# Turn off nyae correction
unsetopt CORRECT

# aliasing
alias top="vtop --theme wizard"
alias j="z"
alias auxg="ps aux | grep -i"
alias gcam="git commit -a -m"
alias sbl="subl ."
alias gmnoff="git merge --no-ff"
alias rmdir="rm -rf"
alias rmrf="rm -rf"
alias kst="kill-session -t"
alias chrome="open -a Google\ Chrome"
alias lsa="ls -a"
alias lsla="ls -la"
alias extract="dtrx"
alias gt="gittower ."
alias gst="git status -sb"
alias gstat="git status"
alias glog="git hist"
alias gstats="while true; do clear; git status -sb; sleep 2; done"
alias glogger="while true; do clear; git hist -5 | cat; sleep 3; done"

#unset rm="rm -i"
unalias rm
# add z 
. `brew --prefix`/etc/profile.d/z.sh
# export
export PATH=./node_modules/.bin:/usr/local/bin:$PATH


# virtualenv
# Disable virtualenv prompt info
export VIRTUAL_ENV_DISABLE_PROMPT='1'
# activate 'default' virtualenv
source /Users/tyler/.virtualenvs/default/bin/activate
